### ISSUE TITLE
Custom symbols

### ISSUE THREAD

**Issue by schurgan** [belzetrigger/domoticz-FritzPresence#2]
Domoticz Version: 2021.1
Python Version: 3.7.3

Hallo, das ist ein sehr nützlicher Plugin, danke dafür. Ein Problem habe ich aber trotzdem. Nach dem Neustart von Domoticz werden immer die benutzerdefinierte Symbole durch die vom Plugin ersetzt. Kann man das verhindern? Danke

**Comment by belzetrigger** [comment]
Hallo,
gerne.  
Zum gemeldeten Issue - bei meinem Schnelltest unter Linux und Domoticz 2020.2 blieben die benutzerdefinierten Symbole bei den Geräten auch bei einem 'sudo systemctl restart domoticz.service' und 'reboot' erhalten.  Die Icons/Symbole werden vom Plugin nur beim Hinzufügen des jeweiligen "Gerätes"  festgelegt. Danach können diese beliebig geändert werden. Obacht, die Symbole/Icons die direkt bei dem Geäten via Bearbeiten geändert wurden. 

Um die Standard-Icon-Sets des Plugins zu überschreiben, müssen die zips im Pluginordner ausgetauscht werden.  Alternativ muss die Funktion `checkImages` angepasst / übersprungen werden. Bei einem Update gehen diese aber verloren.

Ich hoffe es hilft weiter.

**Comment by schurgan** [comment]
Kann es damit zu tun haben, dass ich es so eingerichtet habe, dass ich in dem Feld "Name" alle Gerätenamen, die ich haben wollte, hintereinander weg eingegeben habe und im Feld "MAC Adressen" die dazu gehörenden MACs eingegeben habe. Sonst verstehe ich nicht, warum bei Dir die Symbole bleiben und bei mir sich ändern...

**Comment by schurgan** [comment]
Die ZIPs zu überschreiben macht nicht viel Sinn, denn ich habe mehrere Symbole verändert, es sind viel zu viele. Die Funktion checkImages anpassen kann ich selber bestimmt nicht, hab keine Ahnung von...

**Comment by belzetrigger** [comment]
Danke für den Hinweis mit der Konfiguration via Name und MAC-Adressen. Bei dieser Art der Konfiguration wird derzeit alles erneut initialisiert und damit anscheind leider auch das Bild. Ich habe [hier einen quickfix](https://github.com/belzetrigger/domoticz-FritzPresence/tree/test/schurgan) erstellt. Damit bleiben die Änderungen erhalten. Gerne mal test und eine Rückmeldung, dann kann es in die Hauptversion einfließen.

Ich selbst nutzte eher die Admin, füge alle Elemente hinzu und lösche die, die ich nicht will.

**Comment by schurgan** [comment]
Danke, wie kann ich auf den Zweig umschalten?

**Comment by schurgan** [comment]
Der Name des Plugins im System sieht jetzt so wie auf dem Bild aus. Dementsprechend auch im Protokoll. Kann man das hübscher machen, dass man nicht den ganzen Text seht sondern nur den eigentlichen Namen des Plugins? Ich weis, das kann man machen wenn man nicht mit den MACs arbeitet, sondern wenn man alle bzw. alle aktiven Geräte aus der FritzBox holt. Ich habe z.B. fast 100 Geräte und Löwenanteil brauche ich nicht, sondern nur 23 Geräte und möchte durch den MAC Verfahren gezielt andere Geräte holen bzw. austauschen wenn z.B. neues Handy da ist. Das ding mit den Plugin-Namen finde ich aber unübersichtlich und unschön. Wie meinst du, wäre es möglich? Danke für deine Arbeit. Gruß. Alex[
![FritzPresence](https://user-images.githubusercontent.com/51407784/115232097-a5ec2080-a116-11eb-833f-ef944f19845c.jpg)
](url)

**Comment by belzetrigger** [comment]
Ja, stimme zu es sieht etwas unübersichtlich aus. Am liebsten hätte ich so einen Button wie beim 'Dummy Device' um neue Geräte hinzuzufügen, leider habe ich dafür keinen Weg gefunden. Daher der Workaround via Name.

Die frei verfügbaren Felder in der Konfiguration sind m.E. leider auf sechs begrenzt. Eines könnte noch frei sein. Mögliche Optionen:
1.  Man könnte also eine neues Feld Device-Names nutzen anstatt Name. 
2.  Die Namen einfach MAC-basierend von der FritzBox nutzen. Dort kann man diese ja recht gut administrieren. Nur wenn die MAC unbekannt ist, würde statt dem Namen die MAC angezeigt werden. Aber so sieht man sofort, dass was nicht stimmt. Wäre analog zu den Geräten, die via Admin hinzugefügt werden.
3. Ignorelist einfügen, welche Geräte beim Hinzufügen via Fritz!Presence-Admin von der FritzBox ignoriert werden

Momentan würde ich zu 2. tendieren.

**Comment by schurgan** [comment]
Wei meinst du es mit der 2. Das habe ich jetzt nicht wirklich verstanden. Bei mir in der FritzBox ist alles klar geregelt und alle Geräte umbenannt worden. Soll ich anstatt der MAC Adressen die Namen eingeben?

**Comment by belzetrigger** [comment]
Umgekehrt. Das Plugin kommt ohne die Namensliste aus und verarbeitet einfach die MAC-Liste. Beim Update der Geräte wird der Gerätename dann mit dem Namen aus der Fritz!Box überschrieben. Allerdings ist seitens Domoticz-Python-API das Ändern des Namens nicht voll bzw direkt unterstützt. Über die JSON-API via `http://127.0.01/json.htm?param=renamedevice&type=command&idx=125&name=DEVICENAME` geht es aber. Ich versuche mal einen Test im [branch](https://github.com/belzetrigger/domoticz-FritzPresence/tree/test/schurgan) bereitzustellen.

**Comment by schurgan** [comment]
Kann ich schon testen? Soll ich einfach den Plugin-Namen umbenennen, also die Gerätenamen entfernen?

**Comment by schurgan** [comment]
OK, dann warte ich auf deine Rückmeldung. Danke

**Comment by belzetrigger** [comment]
Leider keinen anderen Weg gefunden als noch in der Konfiguration den Parameter: Port einzufügen. Der Plugin Name wird jetzt ignoriert, es werden nur die MACs verarbeitet.

1. prüfen ob im python die lib `urllib` drin ist
2. plugin.py vom branch aktualisieren
3. ein Gerät raussuchen wo der Name zwischen Domoticz und Fritz nicht passt,  ansonsten z. B. in der FritzBox testweise änder
4.  domoticz neustarten
5. Hardware-Konfiguration port 8080 oder den korrekten eintragen
6. am besten in den Protokollen nach `BLZ: new name!` suchen, das Gerät von 3 sollte hier auftauchen

In der GeräteListe, sollten dann die korrekten Namen angezeigt werden.

Dann Schritt zwei, 

1. Aus dem Plugin-Namen eine Eintrag entfernen, aber in dem Feld MAC drin lassen. 
2. Neustart
3. Prüfen, Device sollte immernoch drin sein.

**Comment by schurgan** [comment]
Es ist alles weg gewesen, der Plugin scheint nicht starten zu können. Ein riesen Lappen von Fehler. Zum Glück konnte ich alles noch mit dem master retten. Also der Plugin verschwand sogar aus der Liste in dem Reiter "Hardware"

**Comment by belzetrigger** [comment]
Die Lib wurde aber mit `sudo python -m pip install urllib3` oder `sudo pip install urllib3` installiert?
Ansonsten ist der Test-Branch so zwischen Version 0.6.4 und 0.7.0. Sprich ich habe die Anpassungen händisch rübergetragen.

**Comment by schurgan** [comment]
Ja mit sudo pip3 install urllib3 habe ich installiert, der war aber anscheinend schon drauf.

**Comment by schurgan** [comment]
Ich hab mit git pull aktualisiet. Dann domoticz service neugestartet und alles lief schief.

**Comment by belzetrigger** [comment]
Danke fürs Feedback. Ich habe noch die plugin.py geprüft. Da hat für den zusätzlichen Konfig-Parameter Port das `/>` gefehlt. Und dann dreht Domoticz völlig durch. Passt also zur Fehlerbeschreibung.

Ansonsten, falls noch nicht gemacht, empfehle ich die automatische Sicherung bei Einstellungen einzuschalten und ein manueller Export über Einrichtung > Einstellungen > Sicher/Wiederherstellen durchzführen.

**Comment by schurgan** [comment]
Der Fehler kommt jetzt:

2021-04-21 22:27:43.920 Error: FritzPresence: (FritzPresence) 'onHeartbeat' failed 'TypeError':''dict' object is not callable'.
2021-04-21 22:27:43.920 Error: FritzPresence: (FritzPresence) ----> Line 501 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat
2021-04-21 22:27:43.920 Error: FritzPresence: (FritzPresence) ----> Line 429 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat

**Comment by schurgan** [comment]
Wau...hab den Fehler selber gefunden
In der Zeile 429

url = "http://localhost:{}/json.htm?param=renamedevice&type=command&idx={}&name={}".format(Parameters('Port'),Devices[x].ID,name)

die Klamer von ('Port') auf ['Port'] geändert, jetzt geht alles bestens

**Comment by schurgan** [comment]
Wollen wir als nächstes den BSR Plugin perfektionieren :) ? Dort habe ich vor paar Tagen auch ein issue aufgemacht...

**Comment by belzetrigger** [comment]
Danke. Für die Rückmeldung und den Ping auf den anderen Issue. Hatte ich übersehen.

Ich werde die Anpassungen dann in die 0.7.0 überführen. Dann wird man jedoch die Fritz!Box User und PW nochmal eingeben müssen, da wie gesagt die Parameter überarbeitet wurden.

**Comment by belzetrigger** [comment]
Die Anpassungen aus dem test-Branch habe ich mit meiner aktuellen Version zusammen geführt. 
**Achtung. User und Passwort müssen neu eingetragen werden.**

Gerne mal Testen - ansonsten würde den Issue schließen.

**Comment by schurgan** [comment]
Danke dir

**Comment by schurgan** [comment]
Hallo,
ich habe gerade auf master gewechselt und bekomme folgende Fehler:
2021-05-15 08:55:02.013 Error: FritzPresence: (FritzPresence) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/domoticz-FritzPresence/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2021-05-15 08:55:02.013 Error: FritzPresence: (FritzPresence) Module Import failed, exception: 'SyntaxError'
2021-05-15 08:55:02.013 Error: FritzPresence: (FritzPresence) Import detail: File: /home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py, Line: 229, offset: 2
2021-05-15 08:55:02.013 Error: FritzPresence: (FritzPresence) Error Line '<<<<<<< HEAD
2021-05-15 08:55:02.013 '

Nach wechseln auf test/schurgan läuft alles wieder fehlerfrei...

**Comment by belzetrigger** [comment]
Hallo. Sieht aus als wenn mein automatischer Merge nicht so recht funktioniert hat.  Dann stehen da immer noch Reste  wie '<<<<<<< HEAD' drin.  Wurde mir leider auch nicht mehr angezeigt. Habe jetzt nochmal manuell gemacht und danach bei mir getestet. Jetzt sollte es gehen, wenn die User/Passwörter neu eingetragen wurden.

**Comment by schurgan** [comment]
Jetzt kommt folgendes:
2021-05-15 13:06:51.101 Error: FritzPresence: (FritzPresence) 'onHeartbeat' failed 'Exception'.
2021-05-15 13:06:51.101 Error: FritzPresence: (FritzPresence) ----> Line 521 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat
2021-05-15 13:06:51.101 Error: FritzPresence: (FritzPresence) ----> Line 438 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat
2021-05-15 13:06:51.102 Error: FritzPresence: (FritzPresence) ----> Line 485 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/fritzhelper/fritzHelper.py', function getDeviceName
2021-05-15 13:06:51.102 Error: FritzPresence: (FritzPresence) ----> Line 260 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/fritzhelper/fritzHelper.py', function validateDeviceIndex

**Comment by belzetrigger** [comment]
Befindet sich im Log auch ein Eintrag "Given index 'xxx' not valid. " Könnte etwas davor oder danach kommen. Statt xxx sollt natürlich was anderes drin stehen. Er versucht eine MAC anzusprechen die er nicht kennt, bzw findet.

Ich habe die Funktion zum Auslesen des Namens auf die Schnelle stabilisiert. Bisher hatte er ja das weggefallene Feld genutzt und jetzt die Daten von der Box.

**Comment by schurgan** [comment]
Geht immer noch nicht. Test/schurgan funktioniert ja sehr gut. Könntest du bitte den Abzweig nicht löschen, ich nutze dann ihn weiter und das Problem ist weg 😄

**Comment by belzetrigger** [comment]
Klar kann ich stehen lassen. Kannst aber auch in dein eigene Fork holen. 
Aber irgendwie scheine ich da was übersehn zu haben und den Bug würde ich schon gerne rausbekommen....

**Comment by belzetrigger** [comment]
Ansonsten habe ich noch einen Patch gemacht. Bei mir tauchte dann im Log auch `Invalid MAC Address on index 2=''` auf. Und das Plugin startet. Allerdings weiß ich nicht, ob bei dir ggf. aus den Anfängen Geräte drin sind, deren ID nicht die MAC sondern was anderes ist.

**Comment by schurgan** [comment]
Naja, mit test dev funktioniert ja... Dann sind die alle MACs richtig

**Comment by schurgan** [comment]
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) Given index '74:AB:93:21:35:54' not valid.
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) error on get name for device with id: '74:AB:93:21:35:54' > Index '74:AB:93:21:35:54' is not valid
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) Given index '74:AB:93:21:35:54' not valid.
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) 'onHeartbeat' failed 'Exception'.
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) ----> Line 521 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) ----> Line 441 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) ----> Line 275 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/fritzhelper/fritzHelper.py', function needsUpdate
2021-05-15 23:42:42.432 Error: FritzPresence: (FritzPresence) ----> Line 260 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/fritzhelper/fritzHelper.py', function validateDeviceIndex

**Comment by belzetrigger** [comment]
Danke. 
Beim Starten werden ja die MACs aus der Konfiguration und ggf. schon exisitierende aus der Domoticz-Geräteliste geholt. Diese werden dann gemeinsam abgearbeitet. Ich habe jetzt auf verschieden weisen versucht den Fehler zu reproduzieren. MACs entfernt, die Reihenfolge geändert, gelöscht,.... Aber ohne dabei einen Fehler zu verursachen.

Ich werde dieses "harte" Fehlerwerfen mal ausbauen und nur ein Error-Log Eintrag machen. Dann arbeitet zu mindest das Plugin weiter. 

Sonst könnte man nur noch das Plugin auf Debug stellen und im Protkoll/Log prüfen, was es beim Starten so treibt.  Dort müsste die MAC dann auch auftauchen.

**Comment by belzetrigger** [comment]
Einen Fall habe ich entdeckt. Wie gesagt, beim Start werden die beiden Listen (Konfiguration und bereits existierende Geräteliste) verarbeitet. Dabei wird verushct auch mit abweichenden Reihenfolgen klar zu kommen. 
Problem ist, wenn neue MACs nicht hinten sondern vorne und vermtl. auch in der Mitte hinzugefügt werden.In der Domoticz Geräteliste ist Position schon belegt, daher wird kein Geräte dafür angelegt. Aber die restliche Logik geht davon aus, dass es vorhanden ist. Daher dann auch immer Index aka idx aka MAC ungültig.

**Comment by schurgan** [comment]
Ich weiß es nicht was ich falsch mache...
Also meine Schritte:
git checkout master
git pull
Und dann starte ich den Plugin neu und bekomme o. g. Fehler
Dann mache ich:
git checkout test/schurgan
git pull
und alles läuft wieder fehlerfrei

**Comment by schurgan** [comment]
Wie kann ich den Abzeig test/schurgan zu meinen repos kopieren?

**Comment by belzetrigger** [comment]
Die Fehlerbehebung ist noch nicht drin. Hatte erstmal dank Deiner Infos diesen Fehler gefunden. Ich teste gerade hier noch den Fix, dauert aber noch.

**Comment by belzetrigger** [comment]
bzgl. git ich nehme an Du bevorzugst die Web-Oberfläche, dann probiere mal in Deinem git repository ob du oben rechts z. B. den Punkt 'fetch upstream'  hast. 
![grafik](https://user-images.githubusercontent.com/45435432/118394402-d86d3880-b644-11eb-9546-2e3cf6410d8e.png)

mehr siehe hier:
https://adrientorris.github.io/github/how-to-update-a-forked-repository-from-the-ui-on-github

**Comment by belzetrigger** [comment]
Fix ist im master drin.

**Comment by schurgan** [comment]
Jetzt kommt folgendes:

2021-05-16 17:15:09.458 Status: FritzPresence: (FritzPresence) Initialized version 0.7.0, author 'belze'
2021-05-16 17:15:09.470 Error: FritzPresence: (FritzPresence) No username / password set - please update setting.
2021-05-16 17:15:09.470 Error: FritzPresence: (FritzPresence) 'onStart' failed 'ValueError'.
2021-05-16 17:15:09.470 Error: FritzPresence: (FritzPresence) ----> Line 485 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onStart
2021-05-16 17:15:09.470 Error: FritzPresence: (FritzPresence) ----> Line 208 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onStart
2021-05-16 17:15:18.795 FritzPresence: (FritzPresence) onHeartbeat called
2021-05-16 17:15:18.795 Error: FritzPresence: (FritzPresence) Uuups. Fritz is None. Try to recreate.
2021-05-16 17:15:20.456 FritzPresence: (FritzPresence) Update #1 Name: FP - Admin nV: 1 sV:
2021-05-16 17:15:20.456 Error: FritzPresence: (FritzPresence) 'onHeartbeat' failed 'IndexError':'tuple index out of range'.
2021-05-16 17:15:20.456 Error: FritzPresence: (FritzPresence) ----> Line 521 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat
2021-05-16 17:15:20.456 Error: FritzPresence: (FritzPresence) ----> Line 438 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py', function onHeartbeat
2021-05-16 17:15:20.456 Error: FritzPresence: (FritzPresence) ----> Line 505 in '/home/pi/domoticz/plugins/domoticz-FritzPresence/fritzhelper/fritzHelper.py', function getDeviceName

**Comment by belzetrigger** [comment]
Hast Du bei der Konfiguration ochmal  username / password eingegeben?

**Comment by schurgan** [comment]
Sie waren zwar drin, aber ich habe sie sicherheitshalber nochmal eingegeben.

**Comment by schurgan** [comment]
Kannst du nicht einfach alles von test/schurgan zu master 1:1 übertragen? Ich meine wenn der Abzweig einwandfrei funktioniert...

**Comment by belzetrigger** [comment]
Normalerwweise hätte ich auch so gemacht. Aber ich war schon länger an der Version 0.7.0 dran, mit diversen Anpassungen und CleanUps - wie z. B. die Domoticz-eigenen Parameter für User/Passwort zu nutzen, anstatt normalen Konfigurationsparametern, um weitere Konfigs unterbringenzu können. 
Den Test-Branch hatte ich auf Basis der letzten 0.6.x Version gemacht.

**Comment by belzetrigger** [comment]
Mit welchem Browser wurde die Konfiguration angepasst und wurde zwischen durch mal der Cache des Browsers geleert.
FireFox z. B. Strg + F5
Ich habe die Erfahurng gemacht, dass es gerade bei Anpassungen wichtig ist. Sonst scheint er manchmal die alten Seiten aus dem Cache zu nutzen.

Ansonsten könntest Du in Domoticz testweise eine neue "Hardware" dafür hinzufügen mit einer oder zwei MACs um mal zu prüfen, ob es generell läuft. Nicht das ein alter Konfig-Parameter quer schießt.

**Comment by schurgan** [comment]
Hallo belzetrigger,
ich hoffe dass du dich mit dem Plugin beschäftigst. Set gestern, nach der Aktualisierung von Domoticz, habe ich folgendes Problem und weis nicht weiter. Wenn ich den Plugin komplett rausschmeiße und neu einrichte funktioniert alles über die Buttons und sobald ich die MACs eingegeben, bekomme ich den Fehler.

2023-02-15 15:47:02.295 Error: FritzPresence: Call to function 'onHeartbeat' failed, exception details:
2023-02-15 15:47:02.301 Error: FritzPresence: Traceback (most recent call last):
2023-02-15 15:47:02.301 Error: FritzPresence: File "/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py", line 521, in onHeartbeat
2023-02-15 15:47:02.301 Error: FritzPresence: _plugin.onHeartbeat()
2023-02-15 15:47:02.301 Error: FritzPresence: File "/home/pi/domoticz/plugins/domoticz-FritzPresence/plugin.py", line 450, in onHeartbeat
2023-02-15 15:47:02.301 Error: FritzPresence: contents = urllib.request.urlopen(url).read()
2023-02-15 15:47:02.301 Error: FritzPresence: File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
2023-02-15 15:47:02.301 Error: FritzPresence: return opener.open(url, data, timeout)
2023-02-15 15:47:02.301 Error: FritzPresence: File "/usr/lib/python3.7/urllib/request.py", line 531, in open
2023-02-15 15:47:02.301 Error: FritzPresence: response = meth(req, response)
2023-02-15 15:47:02.301 Error: FritzPresence: File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
2023-02-15 15:47:02.301 Error: FritzPresence: 'http', request, response, code, msg, hdrs)
2023-02-15 15:47:02.301 Error: FritzPresence: File "/usr/lib/python3.7/urllib/request.py", line 569, in error
2023-02-15 15:47:02.301 Error: FritzPresence: return self._call_chain(*args)
2023-02-15 15:47:02.301 Error: FritzPresence: File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
2023-02-15 15:47:02.301 Error: FritzPresence: result = func(*args)
2023-02-15 15:47:02.301 Error: FritzPresence: File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
2023-02-15 15:47:02.301 Error: FritzPresence: raise HTTPError(req.full_url, code, msg, hdrs, fp)
2023-02-15 15:47:02.301 Error: FritzPresence: urllib.error.HTTPError: HTTP Error 401: Unauthorized

Ich habe 28 Divices die alle in unterschiedlichen Szenarien drin sind...Falls der Plugin nicht laufen sollte, habe ich verloren...
Danke für deine Unterstützung

**Comment by schurgan** [comment]
Fehler gefunden. In der Zeile 448:
   url = "http://**localhost**:{}/json.htm?param=renamedevice&type=command&idx={}&name=}".format(Parameters['Port'],Devices[x].ID,name)
 in plugin.py anstatt localhost die konkrete IP Adresse vom Raspi eingetragen und siehe da...läuft.
Warum das so ist weiß ich nicht...

**Comment by belzetrigger** [comment]
Hallo.
Zu der Fehlermeldung "HTTP Error 401: Unauthorized" - d.h. es werden für den Zugriff auf die URL Zugangsdaten benötigt. 
Bei einigen Installation/Updates der neuen Domoticz Version tauchte bei mir plötzlich auch eine Anmeldemaske auf. Siehe https://github.com/domoticz/domoticz/issues/5463

Normalerweise sollte bei localhost nichts der gleichen passieren. Ich schaue mal ob ich es bei  mir nachstellen kann oder einen alternativen Zugriff finde.

Aber gut das Du einen Workaround gefunden hast.

**Comment by belzetrigger** [comment]
Nachtrag:
Bei mir ging durch eine Upgrade von Domoticz  das trusted Nework verloren:
Unter 2023.1 neu unter Einstellung>Security>Trusted Networks
in 2022.x noch direkt unter Einstellungen > System > Lokales Netzwerk 
Ggf. Prüfen ob neben dem eigen Netzwerk auch 127.0.0.* drin steht.
